version: '2.4'

services:
  app:
    image: ${DOCKER_USER}/niboapi:${PROFILE}
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5000/health${PROFILE}"]
      timeout: 5s
      interval: 15s
      retries: 5
    ports:
     - 5000:5000
    networks:
      app_net:
        ipv4_address: 172.50.0.2
        ipv6_address: 2001:3984:3989::10
  
  postman:
    image: postman/newman
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./postman:/app
    networks:
      - app_net
    working_dir: /app
    entrypoint: ["newman","run"]
    command: ["NiboApp.postman_collection.json"]
    

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.50.0.0/28"
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
